// ⚠️ PLACEHOLDER FILE — DO NOT USE THESE VALUES AS-IS.
//
// This file is normally auto-generated by the FlutterFire CLI and
// contains your Firebase project's real connection details. The
// values below are structurally valid but not connected to any real
// Firebase project — the app will compile with them, but any actual
// Firebase read/write will fail until you replace this file.
//
// To generate the real file:
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure
//   3. Select (or create) your Firebase project, and the platforms
//      this app targets (Web, Android).
// This overwrites this file with your project's real values.
//
// See FIREBASE_SETUP.md at the project root for the full walkthrough.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate real values for it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );
}
